"""add economy fields to user

Revision ID: 1c86d0497009
Revises: d238b772c6f9
Create Date: 2026-05-09 13:48:28.224070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c86d0497009'
down_revision: Union[str, Sequence[str], None] = 'd238b772c6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reputation_points', sa.Integer(), server_default='100', nullable=False))
    op.add_column('users', sa.Column('last_streak_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_streak_date')
    op.drop_column('users', 'reputation_points')
    # ### end Alembic commands ###
