"""add unique constraint for deduplication

Revision ID: 2aaee88b9760
Revises: f283daf06612
Create Date: 2026-05-17 10:26:54.812630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaee88b9760'
down_revision: Union[str, Sequence[str], None] = 'f283daf06612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_external_id_source', 'media_items', ['external_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_external_id_source', 'media_items', type_='unique')
    # ### end Alembic commands ###
