"""add metadata columns to media_items

Revision ID: f283daf06612
Revises: fef7d797eca3
Create Date: 2026-05-17 10:16:41.427837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f283daf06612'
down_revision: Union[str, Sequence[str], None] = 'fef7d797eca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('poster_url', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('media_items', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('media_items', sa.Column('source', sa.String(), nullable=True))
    op.drop_index(op.f('ix_media_items_embedding_hnsw'), table_name='media_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_media_items_embedding_hnsw'), 'media_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('media_items', 'source')
    op.drop_column('media_items', 'external_id')
    op.drop_column('media_items', 'rating')
    op.drop_column('media_items', 'poster_url')
    op.drop_column('media_items', 'genre')
    # ### end Alembic commands ###
